### ISSUE TITLE
Changing the legend fontsize

### ISSUE THREAD

**Issue by AWSisco** [lukelbd/proplot#331]
### Description

Should one be able to set ```fontsize``` directly in the call to ```ax.legend()```? To make the legend ```fontsize``` smaller or larger, I have to update the ```rc``` settings ahead of time since ```ax.legend(fontsize='small')``` has no effect.

### Steps to reproduce

```python
s = np.sin(np.deg2rad(pplt.arange(0,360)))*pplt.arange(1,6).reshape(6,1)

x=np.deg2rad(pplt.arange(0,360))
y=s.T

labels = np.char.add(np.array(['Line ']*6),pplt.arange(1,6).astype('str'))

fig = pplt.figure(refaspect=(2,1.5), share=False)
axs = fig.subplots(ncols=2)

axs.format(xlim=(0,2*np.pi), xlocator=np.pi/2, xformatter='pi')

p0 = axs[0].plot(x=x, y=y, cycle='FlatUI', labels=labels)
p1 = axs[1].plot(x=x, y=y, cycle='FlatUI', labels=labels)

#Setting fontsize has no effect
axs[0].legend(p0, loc='ll', ncol=2, frame=False, fontsize='small')

#Have to set legend.fontsize separately to set to 'small'
with pplt.rc.context({'legend.fontsize': 'small'}):
    axs[1].legend(p1, loc='ll', ncol=2, frame=False)
```
![legend_font](https://user-images.githubusercontent.com/37667176/151614953-372a0b35-c03c-45bb-b1e5-cd46934ad819.png)

**Expected behavior**: Be able to change the legend fontsize directly in ```ax.legend()```

**Actual behavior**: ```ax.legend(fontsize='small')``` has no effect

### Equivalent steps in matplotlib

```python
import matplotlib.pyplot as plt
import numpy as np

s = np.sin(np.deg2rad(np.arange(0,361)))*np.arange(1,7).reshape(6,1)

x=np.deg2rad(np.arange(0,361))
y=s.T

labels = np.char.add(np.array(['Line ']*6),np.arange(1,7).astype('str'))

fig = plt.figure(figsize=(10,4))
axs = fig.subplots(ncols=2)

p0 = axs[0].plot(x, y, label=labels)
p1 = axs[1].plot(x, y, label=labels)

#Setting fontsize works
axs[0].legend()
axs[1].legend(fontsize='small')
```
![mpl_font](https://user-images.githubusercontent.com/37667176/151616412-cdf43c5e-3c4a-4403-8f64-e2820e85fc9f.png)

### Proplot version

matplotlib 3.4.3
proplot 0.9.5

**Comment by lukelbd** [comment]
Thanks, this was definitely a bug. Fixed by 1a6517ff. The new result of your example:

![tmp](https://user-images.githubusercontent.com/19657652/151672405-07e1be87-3bda-4da9-8bfc-6d2e0989520a.png)

**Comment by Mickychen00** [comment]
Hi, has this fix updated into the version 0.9.5?
I am still encountering same issue.

**Comment by lukelbd** [comment]
Unfortunately it is only in the dev version, but you can install the fix with `pip install git+https://github.com/proplot-dev/proplot.git`.

**Comment by rvalenzuelar** [comment]
Hi, I am using Proplot 0.9.7 and get the same issue with fontsize keyword having no effect on the legend. I am using this:
```python
ax.legend(
          handles=[h1,h2,h3],
          loc='right',ncols=1,
          borderpad=0.1,
          fontsize=.1,
          )
```
